version: "3"
services:
  node_server:
    container_name: node_server
    restart: always
    build: .
    ports:
      - "3000:3000"
  database_server:
    container_name: mongo
    image: mongo
    ports:
      - "27027:27027"
    volumes:
      - /mongo_data:/databases/mongo_data